#VariantDir('build', 'src')
#
env = Environment(LIBS=['dl','boost_filesystem', 'boost_program_options'])

#vars = Variables('custrom.py')
#vars.Add('RELEASE', 'Set to 1 do build for release', 0)
#Help(vars.GenerateHelpText(env))

debug = ARGUMENTS.get('debug', 0)
if int(debug):
	env['CCFLAGS'] = ['-g', '-D_trissa_debug_', '-Wall']
else:
	env['CCFLAGS'] = ['-O3', '-Wall']


env['LINKFLAGS']+=['-rdynamic']
#env.Program('trissa', ['Player.cc', 'PlayerFactory.cc', 'Game.cc', 'UI.cc'], variables = vars)
env.Program('trissa', ['Player.cc', 'PlayerFactory.cc', 'Game.cc', 'UI.cc', 'ConfigManager.cc', 'StateManager.cc'], variables = vars)

#dict = env.Dictionary()
#keys = dict.keys();
#keys.sort();
#for key in keys:
#	print '%s: %s'%(key, dict[key])
#
#
#print 'LINKFLAGS:', env.subst('$LINKFLAGS')
