# -*- coding: utf-8 -*-
#VariantDir('build', 'src')
#
Import('*')
#env.Append(CPPPATH = '#sr')

objs += ['#src/Player.cc', '#src/PlayerFactory.cc', '#src/Game.cc', '#src/UI.cc', '#src/UIText.cc', \
         '#src/ConfigManager.cc', '#src/StateManager.cc']
