#VariantDir('build', 'src')
#
env = Environment(CPPPATH=['../'])

debug = ARGUMENTS.get('debug', False)
if debug == True:
	env['CCFLAGS'] = ['-g']
else:
	env['CCFLAGS'] = ['-O3','-Wall']

env.SharedLibrary(['RandomPlayer.cc'], variables = vars)
env.SharedLibrary(['MinmaxPlayer.cc'], variables = vars)
