#VariantDir('build', 'src')
#
env = Environment(CPPPATH=['../'])

debug = ARGUMENTS.get('debug', False)
if debug == True:
	env['CCFLAGS'] = ['-g', '-Wall', '-D_trissa_debug_']
else:
	env['CCFLAGS'] = ['-O3','-Wall']

env.SharedLibrary(['RandomPlayer.cc'], variables = vars)
env.SharedLibrary(['MinmaxPlayer.cc'], variables = vars)
env.SharedLibrary(['HumanPlayer.cc'], variables = vars)
